title: Girisha Goggireddi
description: MBA | Business Analyst | Data & Strategy Enthusiast
url: "https://girishagoggireddi1.github.io"

permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
show_resume_button: true
resume_file: "Girisha Goggireddi_Resume.pdf"

# Social media links
social:
  linkedin: "http://www.linkedin.com/in/girisha-goggireddi"
  github: "https://github.com/girishagoggireddi1"
  email: "lipikareddi@gmail.com"

# Navigation
nav_links:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Advanced Dashboard
    url: /advanced-dashboard/
  - title: SQL Dashboard
    url: /sql-dashboard/
  - title: Contact
    url: /contact/
